---
functional:
  - требование 1
  - требование 2
non-functional:
  - требование 3:  Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - требование 4
implicit:
  - требование 5
  - требование 6
